baseURL = "https://navcoin.org"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
title = "NavCoin - An Easy To Use Decentralised Cryptocurrency"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"

twitter_username = "navcoin"

[taxonomies]
  npip_category = "npip_categories"
  notice_category = "notice_categories"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin.org"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

# Main Menu
[[menu.main]]
    name = "About"
    title = "About"
    weight = 1
    url = "/about-navcoin/"
    identifier = "about-NavCoin"

[[menu.main]]
    name = "Protocol"
    title = "Protocol"
    weight = 1
    identifier = "protocol"
    [[menu.main]]
        name = "Notices"
        title = "Notices"
        weight = 2
        url = "/notices/"
        identifier = "notices"
        parent = "protocol"

[[menu.main]]
    name = "Learn"
    title = "Learn"
    weight = 2
    identifier = "learn"
    depth = 1
    [[menu.main]]
        name = "Getting Started"
        title = "Getting Started"
        weight = 1
        url = "/getting-started/"
        identifier = "getting-started"
        parent = "learn"
    [[menu.main]]
        name = "For Developers"
        title = "For Developers"
        weight = 2
        url = "/for-developers/"
        identifier = "for-developers"
        parent = "learn"
    [[menu.main]]
        name = "Manifestos"
        title = "Manifestos"
        weight = 3
        url = "/manifestos/"
        identifier = "manifestos"
        parent = "getting-started"
    [[menu.main]]
        name = "Buying NavCoin"
        title = "Buying NavCoin"
        weight = 4
        url = "/buying-navcoin/"
        identifier = "buying-navcoin"
        parent = "learn"
    [[menu.main]]
        name = "Community Fund"
        title = "Community Fund"
        weight = 5
        identifier = "community-fund"
        url = "/community-fund/"
        parent="learn"
    [[menu.main]]
        name = "Knowledge Base"
        title = "Knowledge Base"
        weight = 6
        url = "https://info.navcoin.org"
        parent="learn"
    [[menu.main]]
        name = "Merchants"
        title = "Merchants"
        weight = 7
        url = "/merchants/"
        identifier = "merchants"
        parent = "learn"
    [[menu.main]]
        name = "Accepting NavCoin"
        title = "Accepting NavCoin"
        weight = 9
        url = "/how-to-accept-navcoin/"
        identifier = "how-to-accept-navcoin"
        parent = "learn"
    [[menu.main]]
        name = "About This Website"
        title = "About This Website"
        weight = 10
        url = "/about-this-website/"
        identifier = "about-this-website"
        parent = "learn"
    [[menu.main]]
        name = "Contribute"
        title = "Contribute"
        weight = 12
        url = "/contribute/"
        identifier = "contribute"
        parent = "learn"


[[menu.main]]
    name = "Community"
    title = "Community"
    weight = 3
    identifier = "community"
    [[menu.main]]
        name = "Community Hub"
        title = "Community Hub"
        weight = 1
        identifier = "community-hub"
        url = "https://www.navhub.org"
        parent="community"
    [[menu.main]]
        name = "NavTech Servers"
        title = "NavTech Servers"
        weight = 2
        identifier = "navtech-servers"
        url = "https://navtechservers.com/"
        parent="community"
    [[menu.main]]
        name = "NavCommunity"
        title = "NavCommunity"
        weight = 3
        identifier = "navcommunity"
        url = "https://navcommunity.net/"
        parent="community"
    [[menu.main]]
        name = "NavCoin Italia"
        title = "NavCoin Italia"
        weight = 4
        identifier = "navcoin-italia"
        url = "https://www.navcoinitalia.com/"
        parent="community"


[[menu.main]]
    name = "Downloads"
    title = "Downloads"
    weight = 4
    identifier = "downloads"
    [[menu.main]]
        name = "NavCoin Core"
        title = "NavCoin Core"
        weight = 1
        identifier = "navcoin-core"
        url = "/navcoin-core/"
        parent="downloads"
    [[menu.main]]
        name = "NavPay"
        title = "NavPay"
        weight = 2
        identifier = "navpay"
        url = "/navpay/"
        parent="downloads"
    [[menu.main]]
        name = "All Downloads"
        title = "All Downloads"
        weight = 3
        identifier = "all-downloads"
        url = "/downloads/"
        parent="downloads"